### ISSUE TITLE
Upgrade 0.2.0 Error Related to securescreenstatus

### ISSUE THREAD

**Issue by malmaxx** [explosivo22/kwikset-ha#44]
*****HOME ASSISTANT VERSION INFO*****
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest 
*********************************************

Upgraded HACS integration to 0.2.0 and now receive the below error in Home Assistant Core log.  It does not appear to affect lock/unlock functionality within Home Assistant.  Integrated lock is: Kwikset Halo Touch (HALO-FP-01).

Logger: homeassistant.helpers.entity
Source: custom_components/kwikset/device.py:99
Integration: Kwikset Smart Locks ([documentation](https://github.com/explosivo22/kwikset-ha/))
First occurred: 3:18:07 PM (13 occurrences)
Last logged: 3:22:54 PM
Update for lock.front_door fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/config/custom_components/kwikset/entity.py", line 46, in async_update
    await self._device.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 175, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 82, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 201, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 982, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/kwikset/switch.py", line 89, in is_on
    return self._device.secure_screen_status
  File "/config/custom_components/kwikset/device.py", line 99, in secure_screen_status
    return strtobool(str(self._device_information["securescreenstatus"]))
KeyError: 'securescreenstatus'

**Comment by explosivo22** [comment]
What model lock do you have?

**Comment by malmaxx** [comment]
I noted it above but here it is again:

Kwikset Halo Touch (HALO-FP-01).

**Comment by malmaxx** [comment]
If it helps, these errors are generated exactly every 30 seconds.  At this moment there are 231 instances of that error and counting.

**Comment by explosivo22** [comment]
Apologize you did and I missed it. I was on mobile. I will investigate this and get something pushed out.

**Comment by malmaxx** [comment]
No worries and thank you for the quick response! Please let me know if I can provide anything additional.

**Comment by explosivo22** [comment]
Can you try the beta 0.2.1-beta and see if that fixes your issue?

**Comment by malmaxx** [comment]
I installed the beta version and the errors have stopped.  Thanks!

**Comment by hawkins0000** [comment]
Upgraded to beta version, same result. 
Tried alternate browsers, same result.
Verified credentials, same result.
Cleared browser cache, same result.
Rebooted HASS every time.

Please advise.
