### ISSUE TITLE
Unable to interact with Kwikset Aura

### ISSUE THREAD

**Issue by curtisclark** [explosivo22/kwikset-ha#51]
Firstly, thanks for all the fine work. I’m unable to see any status or control my Kwikset Aura.
Integration version: 0.2.1-beta
Lock FW version: 01.03.21.00

Log below:
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/kwikset/device.py:70 
Integration: Kwikset Smart Locks (documentation) 
First occurred: 11:08:23 AM (23 occurrences) 
Last logged: 11:18:53 AM

Update for lock.front_door fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/config/custom_components/kwikset/entity.py", line 46, in async_update
    await self._device.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 158, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 82, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/kwikset/sensor.py", line 52, in state
    if self._device.battery_percentage is None:
  File "/config/custom_components/kwikset/device.py", line 70, in battery_percentage
    return self._device_information["batterypercentage"]
KeyError: 'batterypercentage'

**Comment by explosivo22** [comment]
I will look into this and see what I can get working for you.
