### ISSUE TITLE
Error adding entities for domain lock with platform kwikset

### ISSUE THREAD

**Issue by lefebp** [explosivo22/kwikset-ha#62]
On Home Assistant 2023.8.0 (Running the OS version with Supervisor 2023.07.1, Operating System 10.3, Frontend 20230802.0 - latest).

Upon HA Core update, the integration stopped working, re-adding the lock (deleting the Kwikset integration entry from the Devices & Services section, re-adding the lock again, entering the credentials) is now broken, the credentials are accepted and the "home" is added and showing but locks are not.

Same error showing three times in the logs, one for each of the three "integrations": Lock, Sensor & Switch.

--------------

Logger: homeassistant.components.lock
Source: helpers/entity_platform.py:619
Integration: Lock (documentation, issues)
First occurred: 19:02:40 (2 occurrences)
Last logged: 19:02:40

Error adding entities for domain lock with platform kwikset
Error while setting up kwikset platform for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial'

**Comment by bh56** [comment]
I'm having the same issue.  Got the Refresh Token has been revoked error.  Deleted and tried to re-add, but doesn't load my devices.  Goes through most of the same steps, but doesn't come up with the devices that allows you to add to the area.  Says created configuration, but no devices.

I just updated with the latest Home Assistant Core.
Home Assistant 2023.8.0
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230802.0 - latest


Error Log details
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:619
Integration: Switch (documentation, issues)
First occurred: 9:26:16 PM (10 occurrences)
Last logged: 9:32:52 PM

Error adding entities for domain switch with platform kwikset
Error while setting up kwikset platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial'

**Comment by bh56** [comment]
Update on my above details.  I took a snapshot before the HASS core update.  On a whim I restored the snapshot before the update.  I deleted and re-added the Kwikset integration.  Low and behold it worked as it has in the past.  So, I believe the HASS Core version 2023.8.0 broke something.  Going to hold tight on HASS Core 2023.7.3, which still works.  Hope this helps or will wait for the next HASS Core update and see if HASS fixes whatever it introduced.
