### ISSUE TITLE
Error initializing on 0.3.0

### ISSUE THREAD

**Issue by thayerfox** [explosivo22/kwikset-ha#79]
After updating to 0.3.0 and rebooting the integration does not load.  I tried removing and readding, but I am unable to get past the username/password dialog (Unknown error occurred).

Reverting back to 0.2.3 works.  

Currently running:
Core
2024.10.4
Supervisor
2024.10.3
Operating System
13.2
Frontend
20241002.4

`Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
First occurred: 5:25:12 PM (2 occurrences)
Last logged: 5:27:46 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiokwikset/api.py", line 168, in async_login
    cognito = await self.loop.run_in_executor(None, partial(self._create_cognito_client, username=email),)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiokwikset/api.py", line 238, in _create_cognito_client
    return _cached_cognito(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiokwikset/api.py", line 264, in _cached_cognito
    return pycognito.Cognito(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycognito/__init__.py", line 207, in __init__
    self.client = session.client("cognito-idp", **boto3_client_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/boto3/session.py", line 270, in client
    :type aws_access_key_id: string
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/botocore/session.py", line 841, in create_client
    aws_secret_access_key=None,
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/botocore/client.py", line 83, in create_client
  File "/usr/local/lib/python3.12/site-packages/botocore/client.py", line 150, in _load_service_model
    )
      
  File "/usr/local/lib/python3.12/site-packages/botocore/loaders.py", line 132, in _wrapper
    instance, and that instance *must* provide a
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/botocore/loaders.py", line 377, in load_service_model
    """Load a botocore service model
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
botocore.exceptions.UnknownServiceError: Unknown service: 'cognito-idp'. Valid service names are: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kwikset/config_flow.py", line 104, in async_step_user
    return await self.async_step_select_home()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kwikset/config_flow.py", line 115, in async_step_select_home
    await self.api.async_login(self.username,self.password)
  File "/usr/local/lib/python3.12/site-packages/aiokwikset/api.py", line 180, in async_login
    raise UnknownError from err
aiokwikset.api.UnknownError`

**Comment by thayerfox** [comment]
Just tried [0.3.0-alpha2](https://github.com/explosivo22/kwikset-ha/releases/tag/0.3.0-alpha2) and it also works.

**Comment by explosivo22** [comment]
Crazy. I have ran this thing through the ringer today. I will look at your posted logs and see what is going on. I have more running on 0.3.0 before releasing, but hopefully we can find something.

**Comment by explosivo22** [comment]
> Just tried [0.3.0-alpha2](https://github.com/explosivo22/kwikset-ha/releases/tag/0.3.0-alpha2) and it also works.
> 
> And then I seem to be able to update to 0.3.0 if > I've configured the lock in 0.3.0 a2.
 I'm glad you could get to 0.3.0. I am looking into the specific issue more. Seems to be something with the cognito stuff itself.

**Comment by thayerfox** [comment]
I can experiment more tomorrow but this is what I've done:

Install 0.2.3, configure and add lock
Upgrade to 0.3.0, error.  Remove lock and readd, error.
Downgrade to 0.2.3, configure and add lock 
Upgrade to 0.3.0, error.
Downgrade to 0.2.3, configure and add lock.
Upgrade to 0.3.0a2, error.  Remove lock and readd, works, does not need 2fa this time.
Upgrade to 0.3.0, works.

**Comment by explosivo22** [comment]
> I can experiment more tomorrow but this is what I've done:
> 
> Install 0.2.3, configure and add lock, works
> Upgrade to 0.3.0, error.  Remove lock and readd, error.
> Downgrade to 0.2.3, configure and add lock, works
> Upgrade to 0.3.0, error.
> Downgrade to 0.2.3, configure and add lock.
> Upgrade to 0.3.0a2, error.  Remove lock and readd, works, does not need 2fa this time.
> Upgrade to 0.3.0, works.
> 
> I have done this twice now to reproduce.

Same error in log everytime?

**Comment by explosivo22** [comment]
> I can experiment more tomorrow but this is what I've done:
> 
> Install 0.2.3, configure and add lock, works Upgrade to 0.3.0, error. 

I am able to reproduce this exact same thing.  I did an extra reboot after the reboot to upgrade to 0.3.0 and mine fired up just fine the second reboot.  I don't know why yet, but this seems to be coming from boto3 and pycognito libraries. I have another integration that uses the 'cognito-idp' from boto3 and it had the same error after install, but went away after reboot. I am wondering if this is something weird HACS and HA are doing.

**Comment by Jurykov** [comment]
Had very similar errors upon upgrading.  Would not work on first reboot after updating.  Tried deleting the integration, and re-installing/configuring it.  Ended up with an authentication error.  After reading here, tried a second reboot of Home Assistant and the new integration configured with no issue.  Working fine now.

**Comment by Guruleenyc** [comment]
Experienci this issue too now. I'm on 0.3.0
It started reported 'failed to setup'

Details:
Source: config_entries.py:594
First occurred: November 6, 2024 at 8:12:17 AM (2 occurrences)
Last logged: 5:27:23 AM

Error setting up entry Home for kwikset
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kwikset/__init__.py", line 39, in async_setup_entry
    await client.async_renew_access_token(entry.data[CONF_ACCESS_TOKEN], entry.data[CONF_REFRESH_TOKEN])
  File "/usr/local/lib/python3.12/site-packages/aiokwikset/api.py", line 204, in async_renew_access_token
    cognito = await self._async_authenticated_cognito()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Guruleenyc** [comment]
> Experiencing this issue too now. I'm on 0.3.0
> It started reported 'failed to setup'
> 
> Details:
> Source: config_entries.py:594
> First occurred: November 6, 2024 at 8:12:17 AM (2 occurrences)
> Last logged: 5:27:23 AM
> 
> Error setting up entry Home for kwikset
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/kwikset/__init__.py", line 39, in async_setup_entry
>     await client.async_renew_access_token(entry.data[CONF_ACCESS_TOKEN], entry.data[CONF_REFRESH_TOKEN])
>   File "/usr/local/lib/python3.12/site-packages/aiokwikset/api.py", line 204, in async_renew_access_token
>     cognito = await self._async_authenticated_cognito()
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 

I upgraded Homeassistant core to 2024.11.0 and it resolved this Kwikset issue for me.

**Comment by adpwl1** [comment]
Getting the same error after upgrading to 0.3.2
HA Core 24.11.1
Supervisor 24.11.2
OS 13.2

**Comment by ababij** [comment]
> Getting the same error after upgrading to 0.3.2 HA Core 24.11.1 Supervisor 24.11.2 OS 13.2
> 
> Downgraded to 0.3.1, error Downgraded to 0.3.0 and its working.

I’m having the same issue. Tried upgrading to 0.3.2 and 2 reboots but I got the error. Tried 0.3.1 with 2 reboots and again, same error. Restored my backup running 0.3.0 and it works.

**Comment by explosivo22** [comment]
> > Getting the same error after upgrading to 0.3.2 HA Core 24.11.1 Supervisor 24.11.2 OS 13.2
> > 
> > Downgraded to 0.3.1, error Downgraded to 0.3.0 and its working.
> 
> I’m having the same issue. Tried upgrading to 0.3.2 and 2 reboots but I got the error. Tried 0.3.1 with 2 reboots and again, same error. Restored my backup running 0.3.0 and it works. 

If you upgrade to 0.3.2, can you try to configure the integration and adjust the refresh even if it is single value and then reload the integration. I am curious if this works.

**Comment by thayerfox** [comment]
> > > Getting the same error after upgrading to 0.3.2 HA Core 24.11.1 Supervisor 24.11.2 OS 13.2
> > > Downgraded to 0.3.1, error Downgraded to 0.3.0 and its working.
> > 
> > 
> > I’m having the same issue. Tried upgrading to 0.3.2 and 2 reboots but I got the error. Tried 0.3.1 with 2 reboots and again, same error. Restored my backup running 0.3.0 and it works.
> 
> If you upgrade to 0.3.2, can you try to configure the integration and adjust the refresh even if it is single value and then reload the integration. I am curious if this works.

Yes, that's what I had to do.  Reboots didn't fix it, configured integration (it asked about refresh), then reload to get it to work.

**Comment by adpwl1** [comment]
> > > Getting the same error after upgrading to 0.3.2 HA Core 24.11.1 Supervisor 24.11.2 OS 13.2
> > > Downgraded to 0.3.1, error Downgraded to 0.3.0 and its working.
> > 
> > 
> > I’m having the same issue. Tried upgrading to 0.3.2 and 2 reboots but I got the error. Tried 0.3.1 with 2 reboots and again, same error. Restored my backup running 0.3.0 and it works.
> 
> If you upgrade to 0.3.2, can you try to configure the integration and adjust the refresh even if it is single value and then reload the integration. I am curious if this works.

Woke up and there was an 11.2 core update, so I applied that.  0.3.0 still worked.  Upgraded to 0.3.2, no dice.

Did what you suggested, changed polling from 30 to 31.  Rebooted.  All is well in HA / Kwikset land!

**Comment by ababij** [comment]
> > > Getting the same error after upgrading to 0.3.2 HA Core 24.11.1 Supervisor 24.11.2 OS 13.2
> > > Downgraded to 0.3.1, error Downgraded to 0.3.0 and its working.
> > 
> > 
> > I’m having the same issue. Tried upgrading to 0.3.2 and 2 reboots but I got the error. Tried 0.3.1 with 2 reboots and again, same error. Restored my backup running 0.3.0 and it works.
> 
> If you upgrade to 0.3.2, can you try to configure the integration and adjust the refresh even if it is single value and then reload the integration. I am curious if this works.

That worked for me.  Upgraded to 0.3.2, adjusted the refresh time and did a reload of the integration and everything is working! Just wondering, does a shorter refresh time have any effect on lock battery life?

**Comment by psiess** [comment]
> > > Getting the same error after upgrading to 0.3.2 HA Core 24.11.1 Supervisor 24.11.2 OS 13.2
> > > Downgraded to 0.3.1, error Downgraded to 0.3.0 and its working.
> > 
> > 
> > I’m having the same issue. Tried upgrading to 0.3.2 and 2 reboots but I got the error. Tried 0.3.1 with 2 reboots and again, same error. Restored my backup running 0.3.0 and it works.
> 
> If you upgrade to 0.3.2, can you try to configure the integration and adjust the refresh even if it is single value and then reload the integration. I am curious if this works.

Yup...this fixed it for me too.  Thanks @explosivo22

**Comment by katelovescode** [comment]
> > > > Getting the same error after upgrading to 0.3.2 HA Core 24.11.1 Supervisor 24.11.2 OS 13.2
> > > > Downgraded to 0.3.1, error Downgraded to 0.3.0 and its working.
> > > 
> > > 
> > > I’m having the same issue. Tried upgrading to 0.3.2 and 2 reboots but I got the error. Tried 0.3.1 with 2 reboots and again, same error. Restored my backup running 0.3.0 and it works.
> > 
> > 
> > If you upgrade to 0.3.2, can you try to configure the integration and adjust the refresh even if it is single value and then reload the integration. I am curious if this works.
> 
> Woke up and there was an 11.2 core update, so I applied that. 0.3.0 still worked. Upgraded to 0.3.2, no dice.
> 
> Did what you suggested, changed polling from 30 to 31. Rebooted. All is well in HA / Kwikset land!

Worked for me too, thanks all.
