### ISSUE TITLE
Error adding my lock to the integration

### ISSUE THREAD

**Issue by katelovescode** [explosivo22/kwikset-ha#80]
I'm not sure if this is related to #79 because my error messages are different, but I've also tried uninstalling, reinstalling, I reset my lock's network connection, and rebooted HA a bunch of times and still no luck.  I'm able to put in my username and password, and it finds my home, then I click submit, and then I get a "failed to set up" notice on the integration page.  I have two logs after the attempt, a warning and an error.

Kwikset-HA version: 0.3.0

Running in HA-Container on a Raspberry Pi:
HA Core 2024.9.1
HA Frontend 20240906.0

Warning
```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 8:20:38 PM (1 occurrences)
Last logged: 8:20:38 PM

Detected blocking call to import_module with args ('custom_components.kwikset.lock',) inside the event loop by custom integration 'kwikset' at custom_components/kwikset/__init__.py, line 58: await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please report it to the author of the 'kwikset' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/kwikset/__init__.py", line 58, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
``` 

Error
```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 8:20:38 PM (2 occurrences)
Last logged: 8:25:56 PM

Error setting up entry Humphrey for kwikset
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kwikset/__init__.py", line 58, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2108, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/kwikset/lock.py", line 4, in <module>
    from homeassistant.components.lock import LockEntity, LockState
ImportError: cannot import name 'LockState' from 'homeassistant.components.lock' (/usr/src/homeassistant/homeassistant/components/lock/__init__.py)
```

**Comment by explosivo22** [comment]
Looks like this is coming from your version of core. 2024.10 is when this setting became valid. I guess I forgot to put in a check for older version. I am certain a core update would fix this, but if there is something holding you back I would need to fix this in the integration.

**Comment by katelovescode** [comment]
Ah!  My bad, thanks for pointing me in the right direction, it's working now.  Sorry to raise an alarm for something I should have tried first 😭

**Comment by explosivo22** [comment]
No worries at all. I'm glad it is working for you.
