### ISSUE TITLE
Cannot connect because unable to refresh token: Too many requests

### ISSUE THREAD

**Issue by nickwilsonr** [explosivo22/kwikset-ha#86]
Got the following error after the most recent reboot of HA:

> 2024-12-12 19:00:42.595 WARNING (MainThread) [hass_nabucasa.iot] Cannot connect because unable to refresh token: Too many requests
> 2024-12-12 19:00:45.473 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Tualatin for kwikset
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.13/site-packages/aiokwikset/api.py", line 207, in async_renew_access_token
>     await self.loop.run_in_executor(None, cognito.renew_access_token)
>   File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.13/site-packages/pycognito/__init__.py", line 699, in renew_access_token
>     refresh_response = self.client.initiate_auth(
>         ClientId=self.client_id,
>         AuthFlow="REFRESH_TOKEN_AUTH",
>         AuthParameters=auth_params,
>     )
>   File "/usr/local/lib/python3.13/site-packages/botocore/client.py", line 569, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.13/site-packages/botocore/client.py", line 1023, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> botocore.errorfactory.TooManyRequestsException: An error occurred (TooManyRequestsException) when calling the InitiateAuth operation: Too many requests
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/kwikset/__init__.py", line 41, in async_setup_entry
>     await client.async_renew_access_token(entry.data[CONF_ACCESS_TOKEN], entry.data[CONF_REFRESH_TOKEN])
>   File "/usr/local/lib/python3.13/site-packages/aiokwikset/api.py", line 211, in async_renew_access_token
>     raise _map_aws_exception(err) from err
> aiokwikset.api.UnknownError: Too many requests

It is worth noting that I have rebooted may HA instance SEVERAL times in the last few days, so it's possible I've triggered something on the kwikset side of things, but I figured this was still worth recording because obviously I'm unable to access my locks right now via HA as a result. Is this a situation where I am just going to need to wait and then try reloading or ???

**Comment by nickwilsonr** [comment]
FYI.. Waiting and then reloading resolved the issue. 

Still worth investigating as it may be a good idea to build in some retry/resiliency/caching so that this error doesn't come up for others.
